const quotes = [
    "Hãy đặt khách hàng vào trung tâm của mọi việc bạn làm.",
    "Khởi nghiệp là một hành trình dài, chỉ có những người kiên trì mới có thể đến đích.",
    "Chúng ta cần có khát vọng lớn để làm được những điều lớn.",
    "Muốn có thành công, phải dám thử thách chính mình.",
    "Sự đổi mới và sáng tạo là cốt lõi của doanh nghiệp.",
    "Chúng ta phải tận dụng thời đại số để phát triển đất nước.",
    "Chìa khóa để thành công là học hỏi không ngừng.",
    "Lãnh đạo không phải là ra lệnh, mà là truyền cảm hứng.",
    "Chuyển đổi số không chỉ là công nghệ, mà là cách con người thay đổi tư duy.",
    "Chúng ta phải làm chủ công nghệ, không thể để công nghệ điều khiển chúng ta.",
    "Tầm nhìn quan trọng hơn kế hoạch, nhưng hành động quan trọng hơn tất cả.",
    "Không có đổi mới, không có tương lai.",
    "Hãy thất bại nhanh, học nhanh, và đứng lên nhanh hơn.",
    "Thế giới đang thay đổi nhanh hơn bao giờ hết, và chúng ta phải chạy nhanh hơn.",
    "Muốn thành công, hãy đặt nhân viên vào vị trí trung tâm của sự phát triển.",
    "Khách hàng là người thầy lớn nhất của doanh nghiệp.",
    "Nếu bạn không thay đổi, bạn sẽ bị thay thế.",
    "Chúng ta phải xây dựng một hệ sinh thái công nghệ, không chỉ là một công ty công nghệ.",
    "Sự khác biệt là chìa khóa để tồn tại.",
    "Tất cả những gì bạn cần là sự quyết tâm và một đội ngũ giỏi.",
    "Khi gặp khó khăn, hãy nghĩ đến lý do bạn bắt đầu.",
    "Thời đại 4.0 không dành cho những ai chậm chạp.",
    "Đừng sợ thay đổi, hãy chấp nhận và làm chủ nó.",
    "Người lãnh đạo giỏi là người giúp nhân viên của mình phát triển.",
    "Dám nghĩ, dám làm, dám chịu trách nhiệm.",
    "Mọi cơ hội đều đến từ sự chuẩn bị.",
    "Đường dài mới biết ngựa hay.",
    "Lửa thử vàng, gian nan thử sức.",
    "Học ăn, học nói, học gói, học mở.",
    "Cái khó ló cái khôn.",
    "Hãy theo đuổi đam mê, thành công sẽ theo đuổi bạn.",
    "Không có thành công nào đến dễ dàng, chỉ có những người kiên trì mới đạt được nó.",
    "Không ai có thể thành công mà không trải qua thất bại.",
    "Tri thức là vũ khí mạnh nhất mà con người có thể sử dụng để thay đổi thế giới.",
    "Muốn làm điều lớn lao, trước hết phải làm những điều nhỏ một cách hoàn hảo.",
    "Kẻ chiến thắng là người có thể đứng dậy sau mỗi lần vấp ngã.",
    "Sống không thẹn với lòng, chết không hổ với trời.",
    "Hãy làm những gì bạn yêu thích, và bạn sẽ không phải làm việc một ngày nào trong đời.",
    "Dân là gốc của nước, nếu dân không có thì nước cũng mất.",
    "Không có tri thức, không thể làm chủ được vận mệnh.",
    "Không ai có thể thay đổi quá khứ, nhưng ai cũng có thể thay đổi tương lai.",
    "Sự kiên trì tạo nên kỳ tích.",
    "Tương lai thuộc về những ai tin vào giấc mơ của mình.",
    "Cách duy nhất để làm tốt công việc là yêu thích những gì bạn làm.",
    "Thất bại là cơ hội để bạn bắt đầu lại một cách thông minh hơn.",
    "Chúng ta không ngừng đổi mới, nếu không chúng ta sẽ bị đào thải.",
    "Hãy dũng cảm theo đuổi đam mê của bạn, chúng có thể thay đổi thế giới.",
    "Thành công không phải là điểm đến, mà là hành trình.",
    "Điều quan trọng nhất là không ngừng đặt câu hỏi.",
    "Tôi chưa bao giờ thất bại, tôi chỉ tìm ra 10.000 cách không hoạt động.",
    "Hãy nghĩ lớn, bắt đầu nhỏ, hành động ngay.",
    "Nếu bạn sinh ra trong nghèo khó, đó không phải lỗi của bạn. Nhưng nếu bạn chết trong nghèo khó, đó là lỗi của bạn.",
    "Cơ hội không gõ cửa, bạn phải đi tìm nó.",
    "Không có áp lực, không có kim cương.",
    "Hãy hành động ngay hôm nay, vì ngày mai có thể quá muộn.",
    "Sự kiên trì và lòng quyết tâm đánh bại mọi thử thách.",
    "Đừng chỉ mơ ước, hãy bắt tay vào hành động.",
    "Rủi ro lớn nhất là không dám mạo hiểm.",
    "Nếu bạn không thể giải thích điều gì đó một cách đơn giản, nghĩa là bạn chưa hiểu đủ rõ.",
    "Hãy học từ thất bại của người khác, bạn sẽ không có đủ thời gian để tự thất bại.",
    "Những điều tuyệt vời không bao giờ đến từ vùng an toàn.",
    "Thành công là 1% cảm hứng và 99% mồ hôi.",
    "Cuộc sống quá ngắn để sống một cuộc đời nhỏ bé."
];